### ISSUE TITLE
When within folder, folder displays badge number

### ISSUE THREAD

**Issue by robertybob** [wrp1002/nosettingsbadge#1]
Hey. I’m on iOS 14.8 and my Settings app had a notification badge number because my iCloud is full. 

My Settings app is with a folder - I installed your tweak (1.01), the badge disappears from the Settings icon, but still appears when viewed from the Home Screen.  
![C7F8AFDC-2C6A-42A5-9DD5-C074DF263D32](https://user-images.githubusercontent.com/2610395/149644686-d427e563-0d19-4f4e-93bf-cfe6fe3d8f41.png)
![254C8936-8766-44C8-BDF4-D39394B9851B](https://user-images.githubusercontent.com/2610395/149644693-dc3c0400-f66e-485d-a94a-85feb819cc01.png)

Can you reproduce this?

**Comment by wrp1002** [comment]
should be fixed in the latest version (1.0.2)

**Comment by robertybob** [comment]
Thank you my issue is fixed
